from optilearn.environments.data_loaders.abstract_data_loader import AbstractDataLoader
from optilearn.environments.data_loaders.inference.image_loader import InferenceImageLoader
from optilearn.environments.data_loaders.learning.image_loader import LearningImageLoader
from optilearn.environments.data_loaders.learning.simple_image_loader import SimpleImageLoader
from optilearn.environments.data_loaders.learning.tabular_dataloader import TabularDataLoader
